//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaconPocService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeaconInfo", Namespace="http://schemas.datacontract.org/2004/07/BeaconPocService")]
    public partial class BeaconInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> MajorField;
        
        private System.Nullable<int> MinorField;
        
        private string UiidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Major
        {
            get
            {
                return this.MajorField;
            }
            set
            {
                this.MajorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Minor
        {
            get
            {
                return this.MinorField;
            }
            set
            {
                this.MinorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uiid
        {
            get
            {
                return this.UiidField;
            }
            set
            {
                this.UiidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInfo", Namespace="http://schemas.datacontract.org/2004/07/BeaconPocService")]
    public partial class AppInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBeaconPocService")]
public interface IBeaconPocService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBeaconPocService/GetAppInfo", ReplyAction="http://tempuri.org/IBeaconPocService/GetAppInfoResponse")]
    BeaconPocService.AppInfo GetAppInfo(BeaconPocService.BeaconInfo beaconInfo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBeaconPocService/GetVersion", ReplyAction="http://tempuri.org/IBeaconPocService/GetVersionResponse")]
    string GetVersion();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBeaconPocServiceChannel : IBeaconPocService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BeaconPocServiceClient : System.ServiceModel.ClientBase<IBeaconPocService>, IBeaconPocService
{
    
    public BeaconPocServiceClient()
    {
    }
    
    public BeaconPocServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BeaconPocServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BeaconPocServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BeaconPocServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public BeaconPocService.AppInfo GetAppInfo(BeaconPocService.BeaconInfo beaconInfo)
    {
        return base.Channel.GetAppInfo(beaconInfo);
    }
    
    public string GetVersion()
    {
        return base.Channel.GetVersion();
    }
}
